### ISSUE TITLE
Issue with nested components

### ISSUE THREAD

**Issue by harafat007** [mikelunn/angular2-breadcrumb#3]
Hi Mike,

 The component doesnt seem to be working with nested components. 

 Could you please look into it.

Thanks

**Comment by mikelunn** [comment]
@harafat007 Thanks for opening an issue. For the use-case I was trying to solve, I didn't even think about child routes. I'll look into it when I get a chance.

**Comment by mikelunn** [comment]
@harafat007 I'm finding it more desirable to not display nested route/components in the breadcrumb since in most cases I already have a tabbed interface when using nested routes.
 After modifying the following line in the breadcrumb.component file from 
`if (route.outlet === 'primary')` to `if (route.outlet === 'primary' && route.firstChild)` the child routes are not added to the breadcrumb.

**Comment by harafat007** [comment]
Thanks Mike
